In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
#from numpy import genfromtxt
import io
import math
import random
from sklearn.model_selection import train_test_split

In [2]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [13]:
data = pd.read_excel('/content/drive/MyDrive/NNFL Assignment/data.xlsx');
print(data.shape)

xmin = np.min(data, axis = 0)
xmax = np.max(data, axis = 0)
data = (data- xmin)/(xmax-xmin)

data = data.to_numpy();
print(data.shape)

(3411, 61)
(3411, 61)


In [4]:
m=data.shape[0]
Y=data[:, 60] # class label
X=data[:, 0:60] # feature matrix

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.3, shuffle = True, random_state = 8)

In [6]:
def max_ap(x_ts,x,y):
  p1 = len([i for (i, val) in enumerate(y) if val == 1. ])
  p2 = len([i for (i, val) in enumerate(y) if val == 2. ])
  p3 = len([i for (i, val) in enumerate(y) if val == 3. ])
  p4 = len([i for (i, val) in enumerate(y) if val == 4. ])
  # priors P(y)
  p1, p2, p3 , p4 = p1/(len(y)), p2/(len(y)), p3/(len(y)) , p4/(len(y))
  x1 = np.array([x[i] for (i, val) in enumerate(y) if val == 1. ])
  x2 = np.array([x[i] for (i, val) in enumerate(y) if val == 2. ])
  x3 = np.array([x[i] for (i, val) in enumerate(y) if val == 3. ])
  x4 = np.array([x[i] for (i, val) in enumerate(y) if val == 4. ])
  # evidence P(x)
  e1, e2, e3 , e4 = len(x1)/(len(x)), len(x2)/(len(x)), len(x3)/(len(x)) , len(x4)/(len(x))
  m1 = mean(x1)
  m2 = mean(x2)
  m3 = mean(x3)
  m4 = mean(x4)
  cov1 = np.cov(np.transpose(x1))
  cov2 = np.cov(np.transpose(x2))
  cov3 = np.cov(np.transpose(x3))
  cov4 = np.cov(np.transpose(x4))
  #coeff1 = 1 /((( 2 * 3.14 )** 2 )*np.linalg.det(cov1)** 0.5 )
  #coeff2 = 1 /((( 2 * 3.14 )** 2 )*np.linalg.det(cov2)** 0.5 )
  #coeff3 = 1 /((( 2 * 3.14 )** 2 )*np.linalg.det(cov3)** 0.5 )
  # likelihoods P(x|y)
  l1 = likelihood(x_ts,m1,cov1)
  l2 = likelihood(x_ts,m2,cov2)
  l3 = likelihood(x_ts,m3,cov3)
  l4 = likelihood(x_ts,m4,cov4)
  # Posteriors P(y|x)
  prob1, prob2, prob3 , prob4 = (l1*p1)/e1, (l2*p2)/e2, (l3*p3)/e3 , (l4*p4)/e4
  if max(prob1,prob2,prob3) == prob1:
    return 1.0
  elif max(prob1,prob2,prob3) == prob2:
    return 2.0
  elif max(prob1,prob2,prob3) == prob3:
    return 3.0
  else:
    return 4.0

In [7]:
def mean(array):
  m = []
  for i in range(60):
    m.append(sum(col(array,i))/len(col(array,i)))
  return m

In [8]:
def col(array, i):
  return [row[i] for row in array]

In [9]:
def likelihood(X,u,sig):
  coeff = 1 /((( 2 * 3.14 )** 3.5 )*np.linalg.det(sig)** 0.5 )
  dev = np.array(X)-np.array(u)
  #lik = coeff*np.exp(- 0.5 *np.dot(np.dot(dev,np.linalg.inv(sig)),np.transpose(dev)))
  gauss = -0.5*(np.dot(np.dot(dev,np.linalg.inv(sig)),np.transpose(dev)))
  try:
    lik = coeff*math.exp(gauss)
  except:
    lik = math.inf
  return lik

In [10]:
def conf_mat(y_pred,y_ts):
  confmat = np.zeros((4,4))
  for i in range(len(y_ts)):
    if y_ts[i] == 1.:
      if y_pred[i] == 1.:
        confmat [0][0] += 1
      if y_pred[i] == 2.:
        confmat [0][1] += 1
      if y_pred[i] == 3.:
        confmat [0][2] += 1
      if y_pred[i] == 4.:
        confmat [0][3] += 1

    if y_ts[i] == 2.:
      if y_pred[i] == 1.:
        confmat [1][0] += 1
      if y_pred[i] == 2.:
        confmat [1][1] += 1
      if y_pred[i] == 3.:
        confmat [1][2] += 1
      if y_pred[i] == 4.:
        confmat [1][3] += 1

    if y_ts[i] == 3.:
      if y_pred[i] == 1.:
        confmat [2][0] += 1
      if y_pred[i] == 2.:
        confmat [2][1] += 1
      if y_pred[i] == 3.:
        confmat [2][2] += 1
      if y_pred[i] == 4.:
        confmat [2][3] += 1

    if y_ts[i] == 4.:
      if y_pred[i] == 1.:
        confmat [3][0] += 1
      if y_pred[i] == 2.:
        confmat [3][1] += 1
      if y_pred[i] == 3.:
        confmat [3][2] += 1
      if y_pred[i] == 4.:
        confmat [3][3] += 1
  return confmat


In [14]:
acc = 0
acc1 = 0
acc2 = 0
acc3 = 0
acc4 = 0

p_outputs = []
for b in range(len(X_test)):
  pred_op = max_ap(X_test[b],X_train,Y_train)
  p_outputs.append(pred_op)
confmat = conf_mat(p_outputs,Y_test)
print(confmat)
Acc = (confmat[ 0 ][ 0 ] + confmat[ 1 ][ 1 ] + confmat[ 2 ][ 2 ] + confmat[3][3])/sum(sum(confmat))
Acc1 = confmat[ 0 ][ 0 ]/sum(confmat[ 0 ])
Acc2 = confmat[ 1 ][ 1 ]/sum(confmat[ 1 ])
Acc3 = confmat[ 2 ][ 2 ]/sum(confmat[ 2 ])
Acc4 = confmat[ 3 ][ 3 ]/sum(confmat[ 3 ])
print( 'Overall Accuracy : ' + str(Acc*100))
print( 'Accuracy of class 1 : ' + str(Acc1*100))
print( 'Accuracy of class 2 : ' + str(Acc2*100))
print( 'Accuracy of class 3 : ' + str(Acc3*100))
print( 'Accuracy of class 4 : ' + str(Acc4*100))

[[ 99.  89.  69.   0.]
 [ 73.  97.  85.   0.]
 [ 91.  85.  83.   0.]
 [101.  70.  82.   0.]]
Overall Accuracy : 27.24609375
Accuracy of class 1 : 38.52140077821012
Accuracy of class 2 : 38.03921568627451
Accuracy of class 3 : 32.04633204633205
Accuracy of class 4 : 0.0
